apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-app

    minReplicas: 2
    maxReplicas: 20

    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
    - type: ContainerResource
    containerResource:
      name: memory
      container: app-container
      target:
        type: AverageValue
        averageValue: 500Mi

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      tolerance: 0.05
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max
      
    scaleDown:
    stabilizationWindowSeconds: 300
    tolerance: 0.10
    policies:
    - type: Percent
      value: 20
      periodSeconds: 60
    - type: Pods
      value: 2
      periodSeconds: 60
    selectPolicy: Min



