apiVersion: v1
kind: Pod
metadata:
  name: ml-worker
spec:
  os:
    name: linux
  terminationGracePeriodSeconds: 60
  restartPolicy: Never
  lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 10"]
  initContainers:
    - name: setup-environment
      image: registry.k8s.io/busybox:1.27.2
      command: ['sh', '-c', 'echo "Setting up environment"']
    - name: watcher-sidecar
      image: registry.k8s.io/busybox:1.27.2
      command: ['sh', '-c', 'sleep 60; exit 88']
      restartPolicy: Always
      restartPolicyRules:
      - action: RestartAllContainers
        onExit:
          exitCodes:
            operator: In
            values: [88]
  containers:
  - name: main-application
    image: registry.k8s.io/busybox:1.27.2
    command: ['sh', '-c', 'echo "Application is running"; sleep 3600']
    lifecycle:
        stopSignal: SIGUSR1   